Repository sampadatiwari30/DeshDarshan, pull requests merged in 2025-08, with the labels that each got.

#282 ✅ PR: Added Footer to Crazy Facts Page
  pages/crazyfacts.html
Labels: enhancement, gssoc 25, level 2

#263 🔗 Added Punjab State Page Integration with Map Modal Button
  assets/images/punjab/anandpur-sahib26128.avif
  assets/images/punjab/bhnagra.png
  assets/images/punjab/dance.avif
  assets/images/punjab/golden_temple.jpg
  assets/images/punjab/phulkari.jpg
  assets/images/punjab/punjabi-foods.jpg
  assets/images/punjab/wagah_border.webp
  pages/explore.html
  pages/feedback.html
  pages/punjab.html
Labels: documentation, gssoc 25, level 2

#257 README Documentation Improvements
  README.md
Labels: documentation, gssoc 25, level 2

#326 🔗 Linked Quiz Page Across Website
  feedback.html
  home1.html
  index.html
  pages/about us.html
  pages/contactus.html
  pages/crazyfacts.html
  pages/dance.html
  pages/destination.html
  pages/explore.html
  pages/feedback.html
  pages/festivals.html
  pages/food.html
  pages/heritage.html
  pages/home1.html
  pages/mob_navbar.html
  pages/punjab.html
Labels: documentation, enhancement, gssoc 25, level 3

#425 Added comprehensive Interactive Festival Calendar feature
  README.md
  components/navbar-home.html
  components/navbar.html
  css/festival-calendar.css
  css/festivals.css
  data/festivals.json
  js/festival-calendar.js
  js/navbar-loader.js
  pages/festival-calendar.html
  pages/festivals.html
Labels: enhancement, gssoc 25

#432 🔧 Fix: Broken Navbar on Hidden Destination Page
  pages/destination.html
Labels: bug, gssoc 25

#439 ✅ Fix: Broken Navbar Links for "About Us" and "Explore India" Pages
  pages/feedback.html
Labels: bug, gssoc 25, level 1

#448 Added 7 hidden destinations in every state (Uttarakhand, Delhi, Gujarat, Odisha along with their descriptions.
  assets/images/states/niti_valley.webp
  pages/destination.html
Labels: bug, enhancement, gssoc 25, level 2

#531 Linked Hidden Destinations to About Us page
  pages/destination.html
Labels: gssoc 25, level 1

#520 Back To Top button consistency and implementation
  food-details.html
  index.html
  pages/about-us.html
  pages/arts.html
  pages/best_time.html
  pages/bharatanatyam.html
  pages/crazyfacts.html
  pages/dance.html
  pages/destination.html
  pages/explore.html
  pages/feedback.html
  pages/festival-calendar.html
  pages/festivals.html
  pages/food.html
  pages/heritage.html
  pages/kathak.html
  pages/kuchipudi.html
  pages/learn_lang.html
  pages/manipuri.html
  pages/mohiniyattam.html
  pages/odissi.html
  pages/punjab.html
  pages/quiz.html
Labels: enhancement, gssoc 25, level 1

#553 new Favicon implementation
  assets/images/icons/favicon-32x32.png
  assets/images/icons/favicon/android-chrome-192x192.png
  assets/images/icons/favicon/android-chrome-512x512.png
  assets/images/icons/favicon/apple-touch-icon.png
  assets/images/icons/favicon/favicon-16x16.png
  assets/images/icons/favicon/favicon-32x32.png
  assets/images/icons/favicon/favicon.ico
  assets/images/icons/favicon/site.webmanifest
  index.html
  pages/arts.html
  pages/best_time.html
  pages/bharatanatyam.html
  pages/contact-us.html
  pages/crazyfacts.html
  pages/dance.html
  pages/destination.html
  pages/explore.html
  pages/feedback.html
  pages/festival-calendar.html
  pages/festivals.html
  pages/food-details.html
  pages/food.html
  pages/forgot-password.html
  pages/heritage.html
  pages/kathak.html
  pages/kuchipudi.html
  pages/learn_lang.html
  pages/login.html
  pages/manipuri.html
  pages/mohiniyattam.html
  pages/odissi.html
  pages/punjab.html
  pages/quiz.html
  pages/signup.html
Labels: enhancement, gssoc 25, level 2

#579 Fix: Enforce minimum 10-character limit for message field in feedback…
  js/feedback.js
Labels: enhancement, gssoc 25, level 1

#574 Fix extra spacing between header and content on Festival Calendar page
  css/festival-calendar.css
Labels: gssoc 25, level 2

#612 Reopen : Add Firebase Config to README
  README.md
Labels: documentation, enhancement, gssoc 25, level 1

#608 Fix: Unify footer styling across Home, Feedback, and About Us pages (…
  css/about-us.css
  css/home.css
  index.html
  pages/about-us.html
Labels: enhancement, gssoc 25, level 2

#624 Style: Add consistent footer styling to index.html (home page)
  css/home.css
  index.html
Labels: enhancement, gssoc 25, level 2

#651 Improve Contact Us Form UI
  css/contact-us.css
  pages/contact-us.html
Labels: good first issue, gssoc 25, level 1
