Repository sampadatiwari30/DeshDarshan, pull requests merged in 2025-09, with the labels that each got.

#762 fix(html): correct malformed HTML, dedupe scripts/buttons, add issue panel & image filename fix
  index.html
Labels: documentation, good first issue, gssoc 25

#764 added mobile responsivesness for scroll-to-top button across all pages
  food-details.html
  index.html
  pages/Yoga/yoga.css
  pages/about-us.html
  pages/arts.html
  pages/best_time.html
  pages/bharatanatyam.html
  pages/crazyfacts.html
  pages/dance.html
  pages/destination.html
  pages/explore.html
  pages/feedback.html
  pages/festival-calendar.html
  pages/festivals.html
  pages/food.html
  pages/heritage.html
  pages/kathak.html
  pages/kuchipudi.html
  pages/learn_lang.html
  pages/manipuri.html
  pages/mohiniyattam.html
  pages/odissi.html
  pages/punjab.html
  pages/quiz.html
Labels: bug, gssoc 25

#767 fix: add consistent footer styling with full add-ons on Crazy Facts page
  pages/crazyfacts.html
Labels: bug, gssoc 25

#778 feat: add chatbot button to Yoga page
  pages/Yoga/yoga.css
  pages/yoga.html
Labels: enhancement, gssoc 25

#777 feat: add hamburger and unify Yoga page navbar with site-wide navbar
  pages/Yoga/yoga.css
  pages/yoga.html
Labels: bug, gssoc 25

#802 Add unified scroll-to-top&bottom-button on all pages missing it
  pages/alluri.html
  pages/arts-handicraft/pulkari.html
  pages/arts.html
  pages/bhagat.html
  pages/charminar.html
  pages/contact-us.html
  pages/dadabhai.html
  pages/food-details.html
  pages/forgot-password.html
  pages/fort.html
  pages/gandhi.html
  pages/gateway.html
  pages/minar.html
  pages/personality-pages/kalpana.html
  pages/qutub.html
  pages/rani.html
  pages/state-info.html
  pages/subhash.html
  pages/tajmahal.html
  places/itinerary-charminar.html
  places/itinerary-gateway.html
  places/itinerary-mysorepalace.html
  places/itinerary-qutubminar.html
  places/itinerary-redfort.html
  places/itinerary-tajmahal.html
Labels: enhancement, gssoc 25

#803 Remove namaste and Experience It feature
  css/experience-it.css
  css/fix-overlays.css
  data/experiences.json
  data/food.json
  festivals/Diwali.html
  index.html
  js/experience-it.js
  js/food-details.js
  js/remove-overlays.js
  pages/arts.html
  pages/bharatanatyam.html
  pages/experience-demo.html
  pages/food-details.html
  pages/food.html
  pages/heritage.html
  pages/temples/akshardham.html
Labels: bug, gssoc 25
